import { EventEmitter, inject, Injectable } from "@angular/core";
import { catchError, exhaustMap, filter, findIndex, map, Observable, Subject, take, throwError } from "rxjs";
import { HttpClient, HttpEvent, HttpEventType, HttpHeaders , HttpParams} from "@angular/common/http";
import { Product } from "../Model/Product";

@Injectable()
export class ProductService{
    productList: Product[] = [
        {
          id: "1",
          name: "Nike Galaxy Pro 1000",
          description: "An advanced footwear technology for modern women, offering unmatched comfort and style.",
          brand: "Nike",
          gender: "WOMEN",
          category: "SPORTS",
          size: [6, 7, 8, 9],
          color: ["Black", "Silver"],
          price: 55,
          is_in_inventory: false,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=1",
          slug: "galaxy-pro-1000"
        },
        {
          id: "2",
          name: "Adidas Velocity Stride",
          description: "Perfect blend of performance and elegance. Designed for active women on the go.",
          brand: "Adidas",
          gender: "WOMEN",
          category: "CASUAL",
          size: [7, 8, 9],
          color: ["Red", "Blue"],
          price: 60,
          is_in_inventory: false,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=2",
          slug: "velocity-stride"
        },
        {
          id: "3",
          name: "Puma HyperJump Classic",
          description: "A versatile sneaker built for both fitness and casual outings, made for active women.",
          brand: "Puma",
          gender: "WOMEN",
          category: "CASUAL",
          size: [6, 7, 8],
          color: ["Purple", "White"],
          price: 50,
          is_in_inventory: true,
          items_left: 5,
          imageURL: "https://picsum.photos/200/300?random=3",
          slug: "hyperjump-classic"
        },
        {
          id: "4",
          name: "Reebok AirBoost Runner",
          description: "Experience the next level of comfort with AirBoost. Designed for speed and style.",
          brand: "Reebok",
          gender: "WOMEN",
          category: "RUNNING",
          size: [7, 8, 9, 10],
          color: ["Black", "Gold"],
          price: 75,
          is_in_inventory: true,
          items_left: 2,
          imageURL: "https://picsum.photos/200/300?random=4",
          slug: "airboost-runner"
        },
        {
          id: "5",
          name: "Under Armour Neon Sprint",
          description: "A fashionable, performance-oriented shoe built for those who move fast and stay stylish.",
          brand: "Under Armour",
          gender: "WOMEN",
          category: "SPORTS",
          size: [6, 7, 8, 9],
          color: ["Yellow", "Black"],
          price: 65,
          is_in_inventory: false,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=5",
          slug: "neon-sprint"
        },
        {
          id: "6",
          name: "Nike TurboFlex X",
          description: "Innovative design with cutting-edge materials for ultimate performance and comfort.",
          brand: "Nike",
          gender: "MEN",
          category: "CASUAL",
          size: [8, 9, 10],
          color: ["Blue", "White"],
          price: 85,
          is_in_inventory: true,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=6",
          slug: "turboflex-x"
        },
        {
          id: "7",
          name: "Adidas Vibe Pulse",
          description: "Comfort meets style in this versatile sneaker for modern men with active lifestyles.",
          brand: "Adidas",
          gender: "MEN",
          category: "RUNNING",
          size: [7, 8, 9, 10, 11],
          color: ["Green", "Black"],
          price: 70,
          is_in_inventory: true,
          items_left: 4,
          imageURL: "https://picsum.photos/200/300?random=7",
          slug: "vibe-pulse"
        },
        {
          id: "8",
          name: "Puma SpeedPro Max",
          description: "Unmatched speed and agility, designed for athletes who aim to push their limits.",
          brand: "Puma",
          gender: "MEN",
          category: "SPORTS",
          size: [8, 9, 10],
          color: ["Red", "Black"],
          price: 90,
          is_in_inventory: true,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=8",
          slug: "speedpro-max"
        },
        {
          id: "9",
          name: "Reebok Essence Track",
          description: "A streamlined design offering excellent support and comfort for all-day wear.",
          brand: "Reebok",
          gender: "MEN",
          category: "CASUAL",
          size: [7, 8, 9, 10],
          color: ["White", "Black"],
          price: 55,
          is_in_inventory: false,
          items_left: 2,
          imageURL: "https://picsum.photos/200/300?random=9",
          slug: "essence-track"
        },
        {
          id: "10",
          name: "Nike Velocity Shift",
          description: "Designed for those who require a shoe that combines style and superior performance.",
          brand: "Nike",
          gender: "MEN",
          category: "SPORTS",
          size: [6, 7, 8, 9],
          color: ["Blue", "Yellow"],
          price: 80,
          is_in_inventory: false,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=10",
          slug: "velocity-shift"
        },
        {
          id: "11",
          name: "Adidas Urban Glide",
          description: "A sleek, modern sneaker with urban influences, designed for men on the move.",
          brand: "Adidas",
          gender: "MEN",
          category: "CASUAL",
          size: [8, 9, 10],
          color: ["Black", "Orange"],
          price: 75,
          is_in_inventory: false,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=11",
          slug: "urban-glide"
        },
        {
          id: "12",
          name: "Vans SportWave 360",
          description: "Engineered for the active lifestyle, this shoe provides support for all your adventures.",
          brand: "Vans",
          gender: "WOMEN",
          category: "SPORTS",
          size: [6, 7, 8, 9],
          color: ["Purple", "Silver"],
          price: 85,
          is_in_inventory: false,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=12",
          slug: "sportwave-360"
        },
        {
          id: "13",
          name: "Under Armour Fury Glider",
          description: "Sporty and comfortable, designed to keep up with your fast-paced lifestyle.",
          brand: "Under Armour",
          gender: "WOMEN",
          category: "CASUAL",
          size: [6, 7, 8],
          color: ["Blue", "Green"],
          price: 70,
          is_in_inventory: true,
          items_left: 5,
          imageURL: "https://picsum.photos/200/300?random=13",
          slug: "fury-glider"
        },
        {
          id: "14",
          name: "Puma Turbo Racer",
          description: "Maximum comfort with a stylish design that helps you race through the day.",
          brand: "Puma",
          gender: "MEN",
          category: "RUNNING",
          size: [8, 9, 10],
          color: ["Yellow", "Black"],
          price: 95,
          is_in_inventory: false,
          items_left: 4,
          imageURL: "https://picsum.photos/200/300?random=14",
          slug: "turbo-racer"
        },
        {
          id: "15",
          name: "Nike Ignite Pro",
          description: "The next evolution in running shoes, offering lightweight support and maximum speed.",
          brand: "Nike",
          gender: "WOMEN",
          category: "RUNNING",
          size: [7, 8, 9],
          color: ["Pink", "White"],
          price: 90,
          is_in_inventory: true,
          items_left: 5,
          imageURL: "https://picsum.photos/200/300?random=15",
          slug: "ignite-pro"
        },
        {
          id: "16",
          name: "Adidas CrossFit Runner",
          description: "Engineered for high-intensity workouts with a durable sole and breathable material.",
          brand: "Adidas",
          gender: "WOMEN",
          category: "SPORTS",
          size: [6, 7, 8],
          color: ["Grey", "Black"],
          price: 65,
          is_in_inventory: true,
          items_left: 4,
          imageURL: "https://picsum.photos/200/300?random=16",
          slug: "crossfit-runner"
        },
        {
          id: "17",
          name: "Puma Aero Sprint",
          description: "A lightweight sprint shoe designed for speed and agility, ideal for athletes.",
          brand: "Puma",
          gender: "MEN",
          category: "SPORTS",
          size: [9, 10, 11],
          color: ["Blue", "White"],
          price: 80,
          is_in_inventory: true,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=17",
          slug: "aero-sprint"
        },
        {
          id: "18",
          name: "Reebok Flexi Glide",
          description: "Experience flexible movement with this innovative design made for comfort and performance.",
          brand: "Reebok",
          gender: "MEN",
          category: "CASUAL",
          size: [8, 9, 10],
          color: ["Black", "Silver"],
          price: 60,
          is_in_inventory: false,
          items_left: 2,
          imageURL: "https://picsum.photos/200/300?random=18",
          slug: "flexi-glide"
        },
        {
          id: "19",
          name: "Under Armour Hiker Max",
          description: "Built for long hikes with durable material and high ankle support.",
          brand: "Under Armour",
          gender: "MEN",
          category: "OUTDOORS",
          size: [9, 10, 11],
          color: ["Dark Brown", "Tan"],
          price: 120,
          is_in_inventory: true,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=19",
          slug: "hiker-max"
        },
        {
          id: "20",
          name: "Vans StreetRunner",
          description: "A street-style sneaker combining comfort and durability for the urban explorer.",
          brand: "Vans",
          gender: "WOMEN",
          category: "CASUAL",
          size: [6, 7, 8],
          color: ["White", "Pink"],
          price: 55,
          is_in_inventory: true,
          items_left: 5,
          imageURL: "https://picsum.photos/200/300?random=20",
          slug: "streetrunner"
        },
        {
          id: "21",
          name: "Nike Wave Glider",
          description: "A hybrid design shoe offering performance and comfort for both running and casual wear.",
          brand: "Nike",
          gender: "WOMEN",
          category: "SPORTS",
          size: [6, 7, 8, 9],
          color: ["Blue", "Purple"],
          price: 95,
          is_in_inventory: true,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=21",
          slug: "wave-glider"
        },
        {
          id: "22",
          name: "New Balance FreshRun",
          description: "Engineered for the avid runner, this shoe provides exceptional cushioning and support.",
          brand: "New Balance",
          gender: "MEN",
          category: "RUNNING",
          size: [8, 9, 10],
          color: ["Gray", "Green"],
          price: 105,
          is_in_inventory: true,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=22",
          slug: "freshrun"
        },
        {
          id: "23",
          name: "Converse Chuck 70",
          description: "Classic high-top Converse sneakers with vintage details and durable craftsmanship.",
          brand: "Converse",
          gender: "MEN",
          category: "CASUAL",
          size: [8, 9, 10],
          color: ["Black", "White"],
          price: 65,
          is_in_inventory: true,
          items_left: 4,
          imageURL: "https://picsum.photos/200/300?random=23",
          slug: "chuck-70"
        },
        {
          id: "24",
          name: "Asics Gel Cumulus 22",
          description: "Comfortable and supportive shoes perfect for long-distance running.",
          brand: "Asics",
          gender: "WOMEN",
          category: "RUNNING",
          size: [6, 7, 8],
          color: ["Pink", "White"],
          price: 120,
          is_in_inventory: true,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=24",
          slug: "gel-cumulus-22"
        },
        {
          id: "25",
          name: "Nike Air Zoom Pegasus 39",
          description: "A highly cushioned and breathable running shoe, designed to enhance performance.",
          brand: "Nike",
          gender: "MEN",
          category: "RUNNING",
          size: [9, 10, 11],
          color: ["Red", "Black"],
          price: 130,
          is_in_inventory: true,
          items_left: 4,
          imageURL: "https://picsum.photos/200/300?random=25",
          slug: "air-zoom-pegasus-39"
        },
        {
          id: "26",
          name: "Brooks Glycerin 19",
          description: "A cushioned running shoe for smooth, comfortable strides throughout your run.",
          brand: "Brooks",
          gender: "WOMEN",
          category: "RUNNING",
          size: [6, 7, 8],
          color: ["Gray", "Pink"],
          price: 120,
          is_in_inventory: true,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=26",
          slug: "glycerin-19"
        },
        {
          id: "27",
          name: "Skechers On The Go 600",
          description: "Comfortable sandals designed for all-day wear, with added memory foam cushioning.",
          brand: "Skechers",
          gender: "WOMEN",
          category: "CASUAL",
          size: [6, 7, 8],
          color: ["Black", "Tan"],
          price: 55,
          is_in_inventory: true,
          items_left: 3,
          imageURL: "https://picsum.photos/200/300?random=27",
          slug: "on-the-go-600"
        },
        {
          id: "28",
          name: "Saucony Endorphin Speed 3",
          description: "Built for speed, this high-performance shoe is perfect for runners looking to improve their times.",
          brand: "Saucony",
          gender: "MEN",
          category: "RUNNING",
          size: [9, 10, 11],
          color: ["Black", "Yellow"],
          price: 140,
          is_in_inventory: true,
          items_left: 2,
          imageURL: "https://picsum.photos/200/300?random=28",
          slug: "endorphin-speed-3"
        },
        {
          id: "29",
          name: "Nike Air Force 1 Low",
          description: "A timeless design with premium leather upper and comfortable, cushioned sole.",
          brand: "Nike",
          gender: "MEN",
          category: "CASUAL",
          size: [8, 9, 10],
          color: ["White", "Gray"],
          price: 100,
          is_in_inventory: true,
          items_left: 5,
          imageURL: "https://picsum.photos/200/300?random=29",
          slug: "air-force-1-low"
        },
        {
          id: "30",
          name: "Adidas Ultraboost 22",
          description: "Maximized cushioning for a luxurious feel, designed for those who prioritize comfort and style.",
          brand: "Adidas",
          gender: "WOMEN",
          category: "RUNNING",
          size: [6, 7, 8],
          color: ["Black", "Pink"],
          price: 180,
          is_in_inventory: true,
          items_left: 4,
          imageURL: "https://picsum.photos/200/300?random=30",
          slug: "ultraboost-22"
        }
      ];
    
    lstProductwithBrand = [
      { "productName": "Air Max 90", "brand": "Nike" },
      { "productName": "Ultraboost 22", "brand": "Adidas" },
      { "productName": "Gel-Kayano 29", "brand": "Asics" },
      { "productName": "Suede Classic", "brand": "Puma" },
      { "productName": "Old Skool", "brand": "Vans" },
      { "productName": "Fresh Foam 1080", "brand": "New Balance" },
      { "productName": "Classic Leather", "brand": "Reebok" },
      { "productName": "Clifton 9", "brand": "Hoka One One" },
      { "productName": "All Star Chuck Taylor", "brand": "Converse" },
      { "productName": "Wave Rider 27", "brand": "Mizuno" },
      { "productName": "Air Zoom Pegasus 39", "brand": "Nike" },
      { "productName": "Cloudswift", "brand": "On Running" },
      { "productName": "NMD_R1", "brand": "Adidas" },
      { "productName": "Bondi 8", "brand": "Hoka One One" },
      { "productName": "Classic Slip-On", "brand": "Vans" },
      { "productName": "GT-2000 11", "brand": "Asics" },
      { "productName": "Speed 600", "brand": "Puma" },
      { "productName": "Floatride Energy 4", "brand": "Reebok" },
      { "productName": "FuelCell Rebel", "brand": "New Balance" },
      { "productName": "Wave Inspire 19", "brand": "Mizuno" },
      { "productName": "Air Max 270", "brand": "Nike" },
      { "productName": "Superstar Kids", "brand": "Adidas" },
      { "productName": "GT-1000 Kids", "brand": "Asics" },
      { "productName": "Suede Heart", "brand": "Puma" },
      { "productName": "Authentic Kids", "brand": "Vans" },
      { "productName": "Fresh Foam Arishi", "brand": "New Balance" },
      { "productName": "Classic Leather Kids", "brand": "Reebok" },
      { "productName": "Cloud Kid", "brand": "On Running" },
      { "productName": "Chuck Taylor Kids", "brand": "Converse" },
      { "productName": "Wave Prophecy Kids", "brand": "Mizuno" },
      { "productName": "Under Armour Neon Sprint", "brand": "Under Armour" }
    ]
    
    constructor() {
      // HttpClient is injected here
    }

    
    GetAllProduct(){
      return this.productList;
    }

}